 subprocess.run(
                [
                    "docker",
                    "exec",
                    "postgres",
                    "pg_isready",
                    "-h",
                    "localhost",
                    "-U",
                    "testdb",
                ],