name: CD Pipeline
on:
  workflow_run:
    branches:
      - main
      - 'releases/**'
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull sd816224/dashboard-pipeline:latest
    - name: Delete old docker container
      run: docker rm -f dashboard-container || true
    - name: Run Docker container
      run: docker run -d --name dashboard-container -p 8050:8050 sd816224/dashboard-pipeline:latest
      # run: docker run -d --name dashboard-container -p 8050:8050 sd816224/dashboard-pipeline:latest
