name: CI Pipeline
on:
  push:
    branches: [ "main" ,"docker"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dcokerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run : docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t dashboard-pipeline .
    - name: Tag the Docker image
      run: docker tag dashboard-pipeline:latest sd816224/dashboard-pipeline:latest
    - name: Push to Dockerhub
      run: docker push sd816224/dashboard-pipeline:latest

